name: Deploy Frontend app
on:
  - workflow_dispatch
jobs:
  Deploy-To-S3:
    name: Deploy to S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: ./blog-app
        run: npm ci

      - name: Build application
        working-directory: ./blog-app
        run: npm run build-release

      - name: Configure AWS Credentials from CI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::779574454656:role/ci-role
          aws-region: us-east-1

      - name: Sync folders to S3
        working-directory: ./
        run: sh sync.sh

      - name: Invalidate Cloudfront 
        run: |
         distribution_id=$(aws cloudfront list-distributions --query "DistributionList.Items[?contains(Aliases.Items[], 'blog.k6sandeep.com')].Id" --output text)
         aws cloudfront create-invalidation --distribution-id $distribution_id --paths "/*"




